In [6]:
import pandas as pd

# This code only Checking for read and print CSV file..... Not necessary
# Read the CSV file into a pandas DataFrame 
df = pd.read_csv('/home/subhamde/Desktop/Final Year Project/Stock-Tweets/Data/07-04-2024_data.csv')
df

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER,DATE1
0,ABSLLIQUID,EQ,1000.01,1000.01,999.99,1000.00,1000.00,143202,1432.02,205,140879,98.38,05-Apr-2024
1,BANKETFADD,EQ,48.25,48.95,48.25,48.84,48.33,357822,173.60,256,304593,85.12,05-Apr-2024
2,EBBETF0430,EQ,1395.35,1395.35,1354.72,1358.60,1354.71,16223,220.62,458,15414,95.01,05-Apr-2024
3,EBBETF0433,EQ,1135.00,1135.00,1107.10,1112.26,1117.17,12047,134.19,232,10782,89.50,05-Apr-2024
4,GOLDSHARE,EQ,59.30,59.70,58.95,59.20,59.25,4124663,2441.89,832,4051000,98.21,05-Apr-2024
5,GRINDWELL,EQ,2037.25,2080.00,1976.15,2067.75,2037.25,141250,2897.92,5581,126851,89.81,05-Apr-2024
6,LIQUID,EQ,999.99,1000.01,999.99,1000.00,999.99,962347,9623.49,1775,859812,89.35,05-Apr-2024
7,LIQUIDADD,EQ,1003.17,1003.17,1003.15,1003.17,1002.67,86210,864.83,84,85511,99.19,05-Apr-2024
8,MVGJL,EQ,262.75,262.75,251.80,253.85,259.40,204535,520.96,1588,175040,85.58,05-Apr-2024
9,NIFTY50ADD,EQ,230.20,231.49,229.62,230.67,230.54,219223,506.66,246,217692,99.30,05-Apr-2024
10,PARSVNATH,EQ,15.65,15.95,15.30,15.50,15.60,946144,147.90,1202,808169,85.42,05-Apr-2024
11,POLYMED,EQ,1579.85,1594.90,1557.60,1567.55,1571.95,171236,2711.79,6242,153095,89.41,05-Apr-2024
12,PSUBANK,EQ,727.97,728.64,716.76,726.52,722.58,216799,1566.54,3346,196937,90.84,05-Apr-2024
13,PVTBANKADD,EQ,24.07,24.30,24.02,24.25,24.02,2120596,513.98,920,2083183,98.24,05-Apr-2024
14,ROUTE,EQ,1610.80,1624.60,1610.80,1612.70,1617.95,169277,2731.73,4426,145066,85.70,05-Apr-2024
15,SBIETFPB,EQ,244.60,248.44,242.00,244.95,242.61,46206,112.57,254,45025,97.44,05-Apr-2024
16,SETFNN50,EQ,655.99,662.08,650.60,661.30,655.97,45013,296.78,838,39841,88.51,05-Apr-2024
17,SURANASOL,EQ,46.75,46.75,46.75,46.75,44.55,327060,152.90,1297,327060,100.00,05-Apr-2024
18,VIJAYA,EQ,656.05,671.30,655.80,665.00,656.05,790927,5252.71,8425,730354,92.34,05-Apr-2024

In [2]:
def sort_csv_by_delivery_percentage(csv_file):
    try:
        df = pd.read_csv(csv_file)

        # Sort the DataFrame based on the DELIV_PER column in descending order
        df_sorted = df.sort_values(by='DELIV_PER', ascending=False)

        # Select only the 'SYMBOL' and 'DELIV_PER' columns
        df_sorted_subset = df_sorted[['SYMBOL', 'DELIV_PER']]

        # df_sorted_subset

        # Check if the DataFrame has at least 15 rows
        if len(df_sorted_subset) >= 15:
            # Print only the first 15 rows
            print(df_sorted_subset.head(15))
        else:
            # Print all rows if there are fewer than 15 rows
            print(df_sorted_subset)

        print('CSV file with selected columns sorted in descending order and first 15 rows printed successfully!')

    except FileNotFoundError:
        print(f"Error: CSV file '{csv_file}' not found. Please check the file path.")
    except Exception as e:
        print(f"An error occurred: {e}")

In [3]:
# Replace with your actual CSV file path
csv_file = "/home/subhamde/Desktop/Final Year Project/Stock-Tweets/Data/03-04-2024_data.csv"
sort_csv_by_delivery_percentage(csv_file)

        SYMBOL  DELIV_PER
0      63MOONS     100.00
32   SWELECTES      99.99
16   LIQUIDSBI      99.85
2   BANKETFADD      99.41
9   GOLDETFADD      99.28
10   GOLDSHARE      98.95
15  LIQUIDCASE      98.66
6   EBBETF0433      98.59
5   EBBETF0425      98.50
11    GTLINFRA      98.41
17     LOWVOL1      97.96
8      ESILVER      96.95
22      NIFTY1      96.64
3   BANKNIFTY1      96.33
28   SETFNIF50      96.30
CSV file with selected columns sorted in descending order and first 15 rows printed successfully!